import {
  ArrowDownToLine,
  ArrowUpFromLine,
  Brain,
  ArrowRightLeft,
  Globe,
  Search,
  GitBranch,
  Merge,
  FileText,
  Plug,
  Workflow,
  FlaskConical,
  Bell,
  Mail,
  MessageSquare,
} from 'lucide-react'

export const NODE_TYPES = {
  input: {
    type: 'input',
    label: 'Input',
    category: 'Input/Output',
    color: '#10B981',
    icon: ArrowDownToLine,
    description: 'Workflow starting point',
    handles: { inputs: 0, outputs: 1 },
    defaultConfig: { inputType: 'text', defaultValue: '' },
  },
  llm: {
    type: 'llm',
    label: 'LLM Call',
    category: 'AI',
    color: '#8B5CF6',
    icon: Brain,
    description: 'Call an AI language model',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      provider: 'claude',
      model: 'claude-sonnet-4-20250514',
      systemPrompt: '',
      userPrompt: '',
      temperature: 0.7,
      maxTokens: 1024,
    },
  },
  transform: {
    type: 'transform',
    label: 'Transform',
    category: 'Data',
    color: '#0EA5E9',
    icon: ArrowRightLeft,
    description: 'Transform or reshape data',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: { operation: 'template', template: '', delimiter: '', jsonPath: '', regex: '' },
  },
  api_call: {
    type: 'api_call',
    label: 'API Call',
    category: 'Integration',
    color: '#F59E0B',
    icon: Globe,
    description: 'Make an HTTP API request',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      method: 'GET',
      url: '',
      headers: [],
      body: '',
      authType: 'none',
      authValue: '',
      responseHandling: 'full',
    },
  },
  scrape: {
    type: 'scrape',
    label: 'Web Scrape',
    category: 'Integration',
    color: '#14B8A6',
    icon: Search,
    description: 'Extract content from web pages',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      url: '',
      extractionType: 'fullText',
      selector: '',
      maxPages: 1,
    },
  },
  condition: {
    type: 'condition',
    label: 'Condition',
    category: 'Logic',
    color: '#EAB308',
    icon: GitBranch,
    description: 'Branch based on a condition',
    handles: {
      inputs: 1,
      outputs: 2,
      outputIds: ['true', 'false'],
      outputLabels: ['True', 'False'],
    },
    defaultConfig: {
      conditionType: 'contains',
      compareValue: '',
      trueLabel: 'True',
      falseLabel: 'False',
    },
  },
  merge: {
    type: 'merge',
    label: 'Merge',
    category: 'Data',
    color: '#0EA5E9',
    icon: Merge,
    description: 'Combine multiple inputs',
    handles: {
      inputs: 2,
      inputIds: ['input-0', 'input-1'],
      outputs: 1,
    },
    defaultConfig: { strategy: 'concatenate', separator: '\n', template: '' },
  },
  file: {
    type: 'file',
    label: 'File',
    category: 'Integration',
    color: '#6B7280',
    icon: FileText,
    description: 'Read or write files',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: { operation: 'read', fileType: 'txt', filename: '' },
  },
  output: {
    type: 'output',
    label: 'Output',
    category: 'Input/Output',
    color: '#EF4444',
    icon: ArrowUpFromLine,
    description: 'Workflow result endpoint',
    handles: { inputs: 1, outputs: 0 },
    defaultConfig: { outputType: 'display', label: 'Result' },
  },
  ab_compare: {
    type: 'ab_compare',
    label: 'A/B Compare',
    category: 'AI',
    color: '#F472B6',
    icon: FlaskConical,
    description: 'Compare outputs from multiple LLMs',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      prompt: '',
      systemPrompt: '',
      temperature: 0.7,
      maxTokens: 1024,
      models: [
        { provider: 'claude', model: 'claude-sonnet-4-20250514' },
        { provider: 'openai', model: 'gpt-4o' },
      ],
    },
  },
  notify_slack: {
    type: 'notify_slack',
    label: 'Slack',
    category: 'Notifications',
    color: '#E01E5A',
    icon: Bell,
    description: 'Send a message to Slack',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      webhookUrl: '',
      channel: '',
      username: 'FlowPilot',
      messageTemplate: '{{Input.output}}',
    },
  },
  notify_email: {
    type: 'notify_email',
    label: 'Email',
    category: 'Notifications',
    color: '#3B82F6',
    icon: Mail,
    description: 'Send an email via SMTP',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      to: '',
      subject: 'FlowPilot Notification',
      smtpHost: '',
      smtpPort: 587,
      smtpUser: '',
      smtpPass: '',
      bodyTemplate: '{{Input.output}}',
    },
  },
  notify_discord: {
    type: 'notify_discord',
    label: 'Discord',
    category: 'Notifications',
    color: '#5865F2',
    icon: MessageSquare,
    description: 'Send a message to Discord',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      webhookUrl: '',
      username: 'FlowPilot',
      messageTemplate: '{{Input.output}}',
    },
  },
  sub_workflow: {
    type: 'sub_workflow',
    label: 'Sub-Workflow',
    category: 'Logic',
    color: '#A855F7',
    icon: Workflow,
    description: 'Run another workflow as a step',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      workflowId: '',
      workflowName: '',
    },
  },
  mcp_tool: {
    type: 'mcp_tool',
    label: 'MCP Tool',
    category: 'Integration',
    color: '#EC4899',
    icon: Plug,
    description: 'Call an MCP server tool',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      serverUrl: '',
      toolName: '',
      toolArgs: '{}',
      authHeader: '',
    },
  },
}

export const CATEGORIES = [
  { name: 'Input/Output', types: ['input', 'output'] },
  { name: 'AI', types: ['llm', 'ab_compare'] },
  { name: 'Data', types: ['transform', 'merge'] },
  { name: 'Integration', types: ['api_call', 'scrape', 'file', 'mcp_tool'] },
  { name: 'Notifications', types: ['notify_slack', 'notify_email', 'notify_discord'] },
  { name: 'Logic', types: ['condition', 'sub_workflow'] },
]

export function getNodeColor(type) {
  return NODE_TYPES[type]?.color ?? '#6B7280'
}
