import {
  ArrowDownToLine,
  ArrowUpFromLine,
  Brain,
  ArrowRightLeft,
  Globe,
  Search,
  GitBranch,
  Merge,
  FileText,
} from 'lucide-react'

export const NODE_TYPES = {
  input: {
    type: 'input',
    label: 'Input',
    category: 'Input/Output',
    color: '#10B981',
    icon: ArrowDownToLine,
    description: 'Workflow starting point',
    handles: { inputs: 0, outputs: 1 },
    defaultConfig: { inputType: 'text', defaultValue: '' },
  },
  llm: {
    type: 'llm',
    label: 'LLM Call',
    category: 'AI',
    color: '#8B5CF6',
    icon: Brain,
    description: 'Call an AI language model',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      provider: 'claude',
      model: 'claude-sonnet-4-20250514',
      systemPrompt: '',
      userPrompt: '',
      temperature: 0.7,
      maxTokens: 1024,
    },
  },
  transform: {
    type: 'transform',
    label: 'Transform',
    category: 'Data',
    color: '#0EA5E9',
    icon: ArrowRightLeft,
    description: 'Transform or reshape data',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: { operation: 'template', template: '', delimiter: '', jsonPath: '', regex: '' },
  },
  api_call: {
    type: 'api_call',
    label: 'API Call',
    category: 'Integration',
    color: '#F59E0B',
    icon: Globe,
    description: 'Make an HTTP API request',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      method: 'GET',
      url: '',
      headers: [],
      body: '',
      authType: 'none',
      authValue: '',
      responseHandling: 'full',
    },
  },
  scrape: {
    type: 'scrape',
    label: 'Web Scrape',
    category: 'Integration',
    color: '#14B8A6',
    icon: Search,
    description: 'Extract content from web pages',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: {
      url: '',
      extractionType: 'fullText',
      selector: '',
      maxPages: 1,
    },
  },
  condition: {
    type: 'condition',
    label: 'Condition',
    category: 'Logic',
    color: '#EAB308',
    icon: GitBranch,
    description: 'Branch based on a condition',
    handles: {
      inputs: 1,
      outputs: 2,
      outputIds: ['true', 'false'],
      outputLabels: ['True', 'False'],
    },
    defaultConfig: {
      conditionType: 'contains',
      compareValue: '',
      trueLabel: 'True',
      falseLabel: 'False',
    },
  },
  merge: {
    type: 'merge',
    label: 'Merge',
    category: 'Data',
    color: '#0EA5E9',
    icon: Merge,
    description: 'Combine multiple inputs',
    handles: {
      inputs: 2,
      inputIds: ['input-0', 'input-1'],
      outputs: 1,
    },
    defaultConfig: { strategy: 'concatenate', separator: '\n', template: '' },
  },
  file: {
    type: 'file',
    label: 'File',
    category: 'Integration',
    color: '#6B7280',
    icon: FileText,
    description: 'Read or write files',
    handles: { inputs: 1, outputs: 1 },
    defaultConfig: { operation: 'read', fileType: 'txt', filename: '' },
  },
  output: {
    type: 'output',
    label: 'Output',
    category: 'Input/Output',
    color: '#EF4444',
    icon: ArrowUpFromLine,
    description: 'Workflow result endpoint',
    handles: { inputs: 1, outputs: 0 },
    defaultConfig: { outputType: 'display', label: 'Result' },
  },
}

export const CATEGORIES = [
  { name: 'Input/Output', types: ['input', 'output'] },
  { name: 'AI', types: ['llm'] },
  { name: 'Data', types: ['transform', 'merge'] },
  { name: 'Integration', types: ['api_call', 'scrape', 'file'] },
  { name: 'Logic', types: ['condition'] },
]

export function getNodeColor(type) {
  return NODE_TYPES[type]?.color ?? '#6B7280'
}
